### ISSUE TITLE
Integrate Azure KeyVault + secrets management

### ISSUE THREAD

**Issue by amondal2** [CDCgov/cfa-config-validation#4]
Properly incorporate secrets and KeyVault access so that the app can pull schemas from blob storage instead of locally. The app should be able to access our Azure blob storage from within Docker. Ensure no secrets are exposed in the repo or code.

**Comment by amondal2** [comment]
@zsusswein Per your suggestion, I'll incorporate automated deployments via GH Actions as a part of this (since it will require me to actually figure out how to use secrets + Docker...)

**Comment by zsusswein** [comment]
We're working on something related-ish over in cdcgov/cfa-epinow2-pipeline#32
