### ISSUE TITLE
Swap from requests.txt to poetry (or similar)

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfa-config-validation#6]
## Is your feature request related to a problem? Please describe.
For ease of development as this grows, it might be nice to swap to a fully fledged package manager like [poetry](https://python-poetry.org/). It's made things pretty easy for us, and has been pretty easy to use so far.

## Describe the solution you'd like
Swap to poetry (or maybe something like [uv](https://docs.astral.sh/uv/)).

## Describe alternatives you've considered
Sticking with a `requirements.txt` wouldn't be the worst, just not quite as convenient long term.

## Additional context
[Predict's guidance on python development](https://potential-adventure-637em36.pages.github.io/docs/python_projects.html)

**Comment by amondal2** [comment]
Thanks @natemcintosh ! Yeah I am using poetry for tests but will be good to use it for dependency management as well.
